{
 "title": "V2Ray Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Sum of Download Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "v2ray_traffic_downlink_bytes_total{dimension=\"user\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Sum of Upload Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "v2ray_traffic_uplink_bytes_total{dimension=\"user\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{dimension=\"outbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{dimension=\"outbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{dimension=\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{dimension=\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}