on:
  push: 

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master 
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18" 

      - run: go build .
      - run: tar -zcvf v2ray-exporter-macos.tar.gz v2ray-exporter
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: v2ray-exporter
        env:
          GITHUB_TOKEN: ${{ secrets.ENV_TOKEN }}
